[package]
name = "quad"
version = "0.0.1"
authors = ["odanek <ondrej.danek@gmail.com>"]
edition = "2021"
description = "Rust Game Engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odanek/quad"

[dependencies]
quad_macros = { path = "macros", version = "0.0.1" }
cgm = { path = "../cgm" }
winit = "0.25.0"
log = "0.4.14"
image = "0.23.14"
uuid = { version = "0.8", features = ["v4"] }
downcast-rs = "1.2.0"