[package]
name = "quad"
version = "0.0.1"
authors = ["odanek <ondrej.danek@gmail.com>"]
edition = "2021"
description = "Rust Game Engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odanek/quad"

[dependencies]
quad_macros = { path = "macros", version = "0.0.1" }
cgm = { path = "../cgm" }
anyhow = "1.0.58"
thiserror = "1.0.30"
winit = "0.26.1"
raw-window-handle = "0.4.2"
log = "0.4.14"
image = "0.24.0"
downcast-rs = "1.2.0"
crossbeam-channel = "0.5.1"
futures-lite = "1.12.0"
async-channel = "1.6.1"
async-executor = "1.4.1"
parking_lot = "0.12.0"
wgpu = "0.12.0"
naga = { version = "0.8.0", features = ["wgsl-in"] }
hex = "0.4.3"
bytemuck = "1.9.1"
bytemuck_derive = "1.1.0"
crevice = "0.10.0" # TODO Replace with Encase?
rectangle-pack = "0.4.2"
guillotiere = "0.6.2"
bitflags = "1.3.2"
ab_glyph = "0.2.15"
glyph_brush_layout = "0.2.3"
derive_deref = "1.1.1"
rodio = { version = "0.15", default-features = false, features = ["vorbis"] }
stretch = "0.3.2"
