[package]
name = "quad"
version = "0.0.1"
authors = ["odanek <ondrej.danek@gmail.com>"]
edition = "2021"
description = "Rust Game Engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odanek/quad"

[dependencies]
quad_macros = { path = "macros", version = "0.0.1" }
cgm = { path = "../cgm" }
anyhow = "1.0.52"
thiserror = "1.0.30"
winit = "0.26.0"
raw-window-handle = "0.4.2"
log = "0.4.14"
image = "0.24.0"
uuid = { version = "1.0.0-alpha.1", features = ["v4"] }
downcast-rs = "1.2.0"
crossbeam-channel = "0.5.1"
futures-lite = "1.12.0"
async-channel = "1.6.1"
async-executor = "1.4.1"
parking_lot = "0.12.0"
num_cpus = "1.13.0"
rand = "0.8.4"
wgpu = "0.12.0"
naga = { version = "0.8.0", features = ["wgsl-in", "wgsl-out"] }
hex = "0.4.3"
bytemuck = "1.7.3"
crevice = "0.8.0"   # TODO: Remove this dependency, implement manually?