[package]
name = "quad"
version = "0.0.1"
authors = ["odanek <ondrej.danek@gmail.com>"]
edition = "2018"
description = "Rust Game Engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/odanek/quad"

[dependencies]
winit = "0.24.0"
log = "0.4.14"
image = "0.23.14"
cgm = { git = "https://github.com/odanek/cgm", branch = "main" }
