[package]
name = "quad_macros"
version = "0.0.1"
description = "Quad macros"
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0.26"
proc-macro2 = "1.0.52"
